/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import io.javalin.Javalin;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    //TODO adding lucene
    //TODO Createa a write vecotere Search
    //TODO Creatae a read enpoint
    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        var app = Javalin.create(config ->  {
            config.routes.get(
                    "/test" ,
                    ctx -> ctx.result("Hello World!")
            );
        }).start(8080);
    }
}
