/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import io.javalin.Javalin;
import io.javalin.config.JavalinConfig;
import io.javalin.http.Context;
import org.apache.lucene.analysis.standard.StandardAnalyzer;
import org.apache.lucene.document.Document;
import org.apache.lucene.document.Field;
import org.apache.lucene.document.TextField;
import org.apache.lucene.index.*;
import org.apache.lucene.search.*;
import org.apache.lucene.store.Directory;
import org.apache.lucene.store.FSDirectory;

import java.io.IOException;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Map;
import java.util.function.Consumer;

public class App {


    //TODO i need to figure out where iam i gonna store the index for local and for the volume docker
    //TODO Createa a write vecotere Search
    //TODO Creatae a read enpoint

    record IndexRequest(String title, String content) {}
    private static final String INDEX_PATH = "data/index";
    private static IndexWriter writer;
    private static IndexSearcher searcher;
    private static DirectoryReader reader;

    public static void main(String[] args) throws IOException {
        // initialize Lucene
        var indexConfig = new IndexWriterConfig(new StandardAnalyzer());
        Directory directory = FSDirectory.open(Path.of(INDEX_PATH));
        writer = new IndexWriter(directory, indexConfig);
        reader = DirectoryReader.open(writer);
        searcher = new IndexSearcher(reader);

        // set up Rest endpoints
        Consumer<JavalinConfig> config = javalinConfig -> {
            javalinConfig.routes.post("/index", App::handleIndex);
            javalinConfig.routes.get("/search", App::handleSearch);
        };
        Javalin.create(config).start(8080);
    }

    private static void handleIndex(Context ctx) throws IOException {
        var request = ctx.bodyAsClass(IndexRequest.class);
        var doc = createDocument(request.title(), request.content());
        writer.addDocument(doc);
        writer.commit();
        searcher = new IndexSearcher(DirectoryReader.openIfChanged(reader));
        ctx.status(201);
    }

    private static void handleSearch(Context ctx) throws IOException {
        String queryString = ctx.queryParam("q");
        Query query = new TermQuery(new Term("content", queryString));
        var docs = new ArrayList<Map<String, String>>();
        for (ScoreDoc hit: searcher.search(query, 10).scoreDocs) {
            Document doc = searcher.storedFields().document(hit.doc);
            docs.add(Map.of(
                    "title", doc.get("title"),
                    "content", doc.get("content"))
            );
        }
        ctx.json(docs);
    }

    private static Document createDocument(String title, String content){
        var doc = new Document();
        var titleField = new TextField("title", title, Field.Store.YES);
        var contentField = new TextField("content", content, Field.Store.YES);
        doc.add(titleField);
        doc.add(contentField);
        return doc;
    }

}