### GET request to example server
POST localhost:8080/index
Content-Type: application/json

{
  "title" : "Harry Potter",
  "content": "this is the first chapter of harry books"
}
###

GET localhost:8080/search?q=chapter

###